//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InSourceTransIdCheckAndFix {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InSourceTransIdCheckAndFix.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer text to translation key mapping is wrong..
        /// </summary>
        internal static string AnalyzerDescriptionOn {
            get {
                return ResourceManager.GetString("AnalyzerDescriptionOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer text to translation key mapping required..
        /// </summary>
        internal static string AnalyzerDescriptionToDo {
            get {
                return ResourceManager.GetString("AnalyzerDescriptionToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mismatch Detected: Translation key &apos;{0}&apos; and developer text &apos;{1}&apos; do not match as expected..
        /// </summary>
        internal static string AnalyzerMessageFormatOn {
            get {
                return ResourceManager.GetString("AnalyzerMessageFormatOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The developer text &apos;{0}&apos; needs a corresponding translation key..
        /// </summary>
        internal static string AnalyzerMessageFormatToDo {
            get {
                return ResourceManager.GetString("AnalyzerMessageFormatToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer text mismatch key.
        /// </summary>
        internal static string AnalyzerTitleOn {
            get {
                return ResourceManager.GetString("AnalyzerTitleOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer text needs key.
        /// </summary>
        internal static string AnalyzerTitleToDo {
            get {
                return ResourceManager.GetString("AnalyzerTitleToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add the developer text &apos;{0}&apos; to the list of pending translations..
        /// </summary>
        internal static string CodeFixAddToPendingTranslation {
            get {
                return ResourceManager.GetString("CodeFixAddToPendingTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change: Translation key &apos;{0}&apos; to &apos;{1}&apos; .
        /// </summary>
        internal static string CodeFixExchangeOfTranslationKeys {
            get {
                return ResourceManager.GetString("CodeFixExchangeOfTranslationKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to find.
        /// </summary>
        internal static string CodeFixMessageFormatOn {
            get {
                return ResourceManager.GetString("CodeFixMessageFormatOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace the method &apos;{0}&apos; with &apos;{1}&apos;, using key &apos;{2}&apos; and developer text &apos;{3}&apos;..
        /// </summary>
        internal static string CodeFixReplaceWithOn {
            get {
                return ResourceManager.GetString("CodeFixReplaceWithOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert: Change method &apos;{0}&apos; to &apos;{1}&apos; .
        /// </summary>
        internal static string CodeFixRevertToToDo {
            get {
                return ResourceManager.GetString("CodeFixRevertToToDo", resourceCulture);
            }
        }
    }
}
